Add script to bulk patch all devices in a search
phrida/device-config-tutorial pull request #1
Opened 2020-05-29 22:12 UTC by woulamme

2020-05-29 22:30 UTC, kjeree requested changes

2020-05-29 22:30 UTC, kjeree commented on bulk-patch.js
> +getDevices(`https://api.ciscospark.com/v1/devices${devicesQuery}`).then(devices => {
Isn't `api.ciscospark.com` going away, in favor of `webexapis.com`? Ref. https://developer.webex.com/blog/introducing-the-new-webexapis-com

2020-05-29 22:30 UTC, kjeree commented on bulk-patch.js
> +    axios.patch(url, JSON.stringify(bulkSettings), patchConfig)
`JSON.stringify` could fail, and the `.catch` below will just swallow the exception. What about parsing it on the line above (inside a `try/catch`)?

2020-05-29 22:30 UTC, kjeree commented on bulk-patch.js
> +const parseLinkHeader = require('parse-link-header');
You are mixing single and double quotes. `yarn prettier --write bulk-patch.js ` should fix all such issues.

2020-05-30 10:41 UTC, kjeree approved these changes

2020-06-03 08:41 UTC, phrida commented on bulk-patch.js
> +const ACCESS_TOKEN = "MTFhMTExZWUtMDE5YS00YWU1LWE3NGUtNmFjOTk2YTZhMzA0MjgyZTcyYzgtZWU0_PF84_1eb65fdf-9643-417f-9974-ad72cae0e10f";
Should we hide the access token as we do in the other script?

2020-06-03 08:44 UTC, merged